export const sanitazeOrder = ({ measurement_date, assign, order, start_date, status }) => ({
  id: order.id,
  name: order.name,
  surname: order.surname,
  productType: order.productType,
  date: new Date(start_date),
  address: {
    code: order.code,
    city: order.city,
    street: order.street,
    house: order.house,
    flat: order.flat,
    lat: order.latitude,
    lng: order.longitude,
  },
  phone: order.phone,
  email: order.email,
  description: order.message,
  priority: status,
  assigned: assign,
  orderDate: measurement_date ? new Date(measurement_date) : measurement_date,
});
